### ISSUE TITLE
`gigahorsetest.AhcClientSpec` fails in the Scala community build

### ISSUE THREAD

**Issue by SethTisue** [eed3si9n/gigahorse#29]
I keep seeing this:

```
[gigahorse] [error] Failed tests:
[gigahorse] [error] 	gigahorsetest.AhcClientSpec
```

```
[gigahorse] [info] http.websocket(r)
[gigahorse] [info] - should open a websocket connection and exchange messages *** FAILED ***
[gigahorse] [info]   java.net.ConnectException: Connection refused: echo.websocket.org/174.129.224.73:80
[gigahorse] [info]   at gigahorse.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:168)
[gigahorse] [info]   at gigahorse.shaded.ahc.org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:103)
[gigahorse] [info]   at gigahorse.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
[gigahorse] [info]   at gigahorse.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
```

I have seen in both locally (on OS X) and on our Jenkins (Linux)

for now, I will disable gigahorse's test suite in the community build (https://github.com/scala/community-builds/commit/6b7a86986785cf8f6668c541688f069c293532d9), but that's a very big hammer. it would be better if either the underlying problem were fixed, or if some more fine-grained way to skip this test in particular was provided (by exiling it to a separate subproject, or by providing an environment variable to disable it, or whatever)

**Comment by eed3si9n** [comment]
Looks like ws://echo.websocket.org is not always responsive, so I replaced it with an echo server using Unfiltered.

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/commit/9db9aab5485b4e1e39e897e61221f788e82712ab

`[info] Project gigahorse---------------: SUCCESS (project rebuilt ok)`
