### ISSUE TITLE
Stream#underlying should return A instead of Unit?

### ISSUE THREAD

**Issue by xuwei-k** [eed3si9n/gigahorse#52]
procedure syntax 😢 

We should fix

```diff
- def underlying[A]
+ def underlying[A]: Unit
```

or

```diff
- def underlying[A]
+ def underlying[A]: A
```

? 🤔 

- https://github.com/eed3si9n/gigahorse/blob/f595d6d5aea708ee1e08f92500311d002676b4fc/core/src/main/scala/gigahorse/Stream.scala#L22-L26
- https://github.com/eed3si9n/gigahorse/blob/f595d6d5aea708ee1e08f92500311d002676b4fc/asynchttpclient/src/main/scala/gigahorse/support/asynchttpclient/AhcStream.scala#L24-L28
- https://github.com/eed3si9n/gigahorse/blob/f595d6d5aea708ee1e08f92500311d002676b4fc/akka-http/src/main/scala/gigahorse/support/akkahttp/AkkaHttpStream.scala#L26-L30

**Comment by eed3si9n** [comment]
It should be def underlying[A]: A.
